backend:
  name: github
  repo:  yami-aka/YamiAccountBlog

media_folder: "static/images"
public_folder: "images/"

collections:
  - label: "blog"
    name: "blog"
    folder: "content/{{year}}/{{month}}"
    create: true
    slug: "{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime"}
      - {label: "タグ", name: "tags", widget: "list"}
      - {label: "本文", name: "body", widget: "markdown"}